name: xhydro_lstm
channels:
  - conda-forge
dependencies:
  - python >=3.12,<3.13
  # Docs
  - ipykernel
  - ipython >=8.5.0
  - jupyter_client
  - libnetcdf
  - nbsphinx >=0.9.5
  - sphinx >=7.1.0,<8.2.0
  - sphinx-autodoc-typehints
  - sphinx-codeautolink >=0.16.2
  - sphinx-copybutton
  - sphinx-intl
  - sphinx-rtd-theme >=1.0
