name: xhydro_lstm
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.14
  - charset-normalizer >=3.1.0
  - netcdf4 # Pinning in RavenPy and xhydro complicate the versioning here.
  - numpy >=1.25.0
  - scikit-learn >=1.2.0
  # - tensorflow # "Do not install TensorFlow with conda. It may not have the latest stable version. pip is recommended since TensorFlow is only officially released to PyPI."
  - xarray >=2023.11.0
  - xhydro
  # Dev tools and testing
  - pip >=25.2
  - bump-my-version >=1.2.3
  - coverage >=7.5.0
  - deptry >=0.23.1
  - flake8 >=7.3.0
  - flake8-rst-docstrings >=0.4.0
  - flit >=3.11.0,<4.0
  - mypy >=1.18.2
  - numpydoc >=1.9.0
  - pooch >=1.8.0
  - pre-commit >=3.5.0
  - pytest >=8.3.2
  - pytest-cov >=5.0.0
  - ruff >=0.13.3
  - tox >=4.30.3
  - vulture >=2.14
  - watchdog >=4.0.0
